# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ludo.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menuNew_Game = QtWidgets.QMenu(self.menubar)
        self.menuNew_Game.setObjectName("menuNew_Game")
        self.menuReset_Game = QtWidgets.QMenu(self.menubar)
        self.menuReset_Game.setObjectName("menuReset_Game")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1_Player = QtWidgets.QAction(MainWindow)
        self.action1_Player.setObjectName("action1_Player")
        self.action2_Players = QtWidgets.QAction(MainWindow)
        self.action2_Players.setObjectName("action2_Players")
        self.action3_Players = QtWidgets.QAction(MainWindow)
        self.action3_Players.setObjectName("action3_Players")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_Game = QtWidgets.QAction(MainWindow)
        self.actionSave_Game.setObjectName("actionSave_Game")
        self.actionLoad_Game = QtWidgets.QAction(MainWindow)
        self.actionLoad_Game.setObjectName("actionLoad_Game")
        self.actionReset_Game = QtWidgets.QAction(MainWindow)
        self.actionReset_Game.setObjectName("actionReset_Game")
        self.actionHow_To_Play = QtWidgets.QAction(MainWindow)
        self.actionHow_To_Play.setObjectName("actionHow_To_Play")
        self.actionAbout_Ludo = QtWidgets.QAction(MainWindow)
        self.actionAbout_Ludo.setObjectName("actionAbout_Ludo")
        self.action4_Players = QtWidgets.QAction(MainWindow)
        self.action4_Players.setObjectName("action4_Players")
        self.actionLoad_Game_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_Game_2.setObjectName("actionLoad_Game_2")
        self.actionSave_Game_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_Game_2.setObjectName("actionSave_Game_2")
        self.menuNew_Game.addAction(self.action1_Player)
        self.menuNew_Game.addAction(self.actionLoad_Game_2)
        self.menuNew_Game.addSeparator()
        self.menuNew_Game.addAction(self.actionSave_Game_2)
        self.menuNew_Game.addSeparator()
        self.menuNew_Game.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHow_To_Play)
        self.menuHelp.addAction(self.actionAbout_Ludo)
        self.menubar.addAction(self.menuNew_Game.menuAction())
        self.menubar.addAction(self.menuReset_Game.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuNew_Game.setTitle(_translate("MainWindow", "New"))
        self.menuReset_Game.setTitle(_translate("MainWindow", "Reset &Game"))
        self.menuHelp.setTitle(_translate("MainWindow", "He&lp"))
        self.action1_Player.setText(_translate("MainWindow", "New Game"))
        self.action2_Players.setText(_translate("MainWindow", "2 Players"))
        self.action3_Players.setText(_translate("MainWindow", "3 Players"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSave_Game.setText(_translate("MainWindow", "Save Game"))
        self.actionLoad_Game.setText(_translate("MainWindow", "Load Game"))
        self.actionReset_Game.setText(_translate("MainWindow", "Reset Game"))
        self.actionHow_To_Play.setText(_translate("MainWindow", "How To Play"))
        self.actionAbout_Ludo.setText(_translate("MainWindow", "About Ludo"))
        self.action4_Players.setText(_translate("MainWindow", "4 Players"))
        self.actionLoad_Game_2.setText(_translate("MainWindow", "Load Game"))
        self.actionSave_Game_2.setText(_translate("MainWindow", "Save Game"))

